Feature/illifcheckedoutrepair
lsulibraries/SirsiDynexFunctionalTests pull request #6
Opened 2020-01-10 22:35 UTC by GarrettArm

Have manually tested this in the browser debug panel, but haven't run the Functional Tests against it. The changes work for both the live site & the updated site.  

Live site was fine with the async complete listener, but Sirsi took that away in the updated server.  So, this uses a plain setInterval.

2020-01-13 15:34 UTC, sullivan1lsu commented on our_files/custom.js
> +  scheduleILLIfCheckedOut = setInterval(ILLIfCheckedOut, 300);
Can we explicitly declare this somewhere so we all know the scope of it?

2020-01-13 15:36 UTC, sullivan1lsu commented on our_files/custom.js
>  var ILLIfCheckedOut = function () {
Can you put in place a new comment with the format:

/*
Purpose: ???
Example URL: ???

Desktop Incoming Markup: TBD
Desktop Outgoing Markup: TBD

Mobile Incoming Markup: TBD
Mobile Outgoing Markup: TBD
*/

So we can all more easily understand what this expects and what it is doing.

2020-01-13 15:37 UTC, sullivan1lsu requested changes
Can you test this out agains the mobile site as well and submit both in this PR?

2020-01-15 16:25 UTC, GarrettArm commented
This change is probably unnecessary.  I understand this problem may be a timing issue between when ILLiadCheckedOut() runs versus when the target element gets created.  On the live site, the function works every time I've observed.  Changing it to a setInterval versus ajax onComplete approach, this may be irrelevant.
Either way, this shoudn't go directly into master.  I'm closing the request & maybe killing the feature/illifcheckedoutrepair branch.

2020-01-15 16:25 UTC, closed without merging